[package]
name = "kittengrid-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kittengrid-agent"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
log = "0.4"
clap = { version = "4.0.10", features = ["derive", "env"] }
env_logger = "0.9"
axum = "0.6.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.83"
git2 = "0.15.0"
tokio = { version = "1", features = ["full"] }
compose_rust = { git = "ssh://git@github.com/kittengrid/compose_rust.git" }
once_cell = "1.17"
thiserror = "1.0"
tempfile = "3.3.0"
url = "2.3.1"
sha2 = "0.10.6"
arc-swap = "1.6.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]