[package]
name = "kittengrid-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "kittengrid-agent"
path = "src/main.rs"

[dependencies]
log = "0.4"
clap = { version = "4.5.3", features = ["derive", "env"] }
env_logger = "0.9"
axum = "0.7.4"
axum-extra = "0.9.2"

serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
tokio = { version = "1", features = ["full"] }
once_cell = "1.19"
thiserror = "1.0"
tempfile = "3.10"
url = "2.5"
sha2 = "0.10"
arc-swap = "1.7"
reqwest = { version = "0.12", features = ["json"] }
boringtun = { version = "0.6.0", features = ["device"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
base64 = "0.22.1"
rtnetlink = "0.14.1"
futures = "0.3.11"
wireguard-rs   = { git = "https://github.com/kittengrid/wireguard-rs.git" }

[dependencies.x25519-dalek]
version = "^1.1"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]
