[package]
name = "kittengrid-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kittengrid-agent"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
log = "0.4"
clap = { version = "4.5.3", features = ["derive", "env"] }
env_logger = "0.9"
axum = "0.7.4"
axum-extra = "0.9.2"

serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
tokio = { version = "1", features = ["full"] }
once_cell = "1.19"
thiserror = "1.0"
tempfile = "3.10"
url = "2.5"
sha2 = "0.10"
arc-swap = "1.7"
reqwest = { version = "0.12", features = ["json"] }

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]
