
services:
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    working_dir: /app
    user: "${HOST_UID:?please set it to $(id -u) and rerun the command}:${HOST_GID:?please set it to $(id -g) and rerun the command}"
    stdin_open: true
    tty: true
    init: true
    networks:
      kittengrid:
    command: bash
    volumes:
      - .:/app
      - ./tmp/home:/home/kittengrid
      - ./docker/resolv.conf:/etc/resolv.conf

networks:
  kittengrid:
    name: kittengrid_kittengrid
    external: true
