x-agent: &agent
  build:
    context: .
    dockerfile: docker/Dockerfile
    target: dev
  working_dir: /app
  environment:
    RUST_TRACING: debug
    CARGO_TARGET_DIR: "/cargo-target/target"
  user: root
  stdin_open: true
  tty: true
  init: true
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  networks:
    kittengrid:
  volumes:
    - .:/app
    - ./tmp/home:/home/kittengrid
    - ./docker/resolv.conf:/etc/resolv.conf
    - ./.env.local:/.env.local
    - target:/cargo-target

services:
  agent-01:
    <<: *agent
    ports:
      - 3001:3000

  agent-02:
    <<: *agent
    ports:
      - 3002:3000

  build-container:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: build
    working_dir: /app
    user: root
    tty: true
    volumes:
      - .:/app
    entrypoint: bash


networks:
  kittengrid:
    name: kittengrid_kittengrid
    external: true

volumes:
  target:
