#!/usr/bin/env bash

# Purpose:
#
# Builds the docker images.

set -e
[ -z "${DEBUG}" ] || set -x

SHA=$(git rev-parse HEAD || '')
IMAGE=ghcr.io/kittengrid/kittengrid-agent
TARGET=${TARGET:-build}
BRANCH=$(git symbolic-ref -q --short HEAD || echo $GITHUB_BASE_REF)

cd "$(dirname "$0")/.."

# parse the option parameters
for i in "$@"; do
  case $i in
    no-cache)
      NO_CACHE="--no-cache"
      shift
    ;;
  esac
done

if [ -n "${CI}" ]; then
    DOCKER_BUILDKIT=1 docker buildx create --driver docker-container --use
fi
DOCKER_BUILDKIT=1 docker buildx build --target $TARGET $NO_CACHE -t $IMAGE:$SHA -f docker/Dockerfile \
		  --cache-from type=registry,ref=${IMAGE}:ci-cache-${BRANCH} \
		  --cache-from type=registry,ref=${IMAGE}:ci-cache-main \
		  --cache-to type=registry,ref=${IMAGE}:ci-cache-${BRANCH},mode=max \
		  --pull --push \
		  .
